# Generated by Django 4.2.27 on 2026-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_photos/'),
        ),
    ]
