# Generated by Django 4.2.27 on 2026-03-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='search_index',
            field=models.TextField(blank=True, null=True),
        ),
    ]
